name: flutterportfoliobyincrease
description: "My portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.6.0
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# To launch run: dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.1
# To launch run: dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
flutter_native_splash:
  color: "#212121"
  image: "assets/images/splash.PNG"
flutter_icons:
  image_path: "assets/images/horse.png"
  android: true
  ios: true
  web:
   generate: true
   image_path: "assets/images/splash.PNG"


flutter:
  uses-material-design: true
  assets:
   - assets/images/