// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADGquVzUKCGcOh_jfQLhG4KlK_7R0LTJk',
    appId: '1:221648431679:web:5db4897c7de8f89eca668a',
    messagingSenderId: '221648431679',
    projectId: 'increasecodes',
    authDomain: 'increasecodes.firebaseapp.com',
    storageBucket: 'increasecodes.appspot.com',
    measurementId: 'G-R14MLDM8XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pIkXVEra2ROFkG4QMQVy4qiDtBJosAw',
    appId: '1:221648431679:android:ac8da1af71a289a0ca668a',
    messagingSenderId: '221648431679',
    projectId: 'increasecodes',
    storageBucket: 'increasecodes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtiO0-rKwQGYoF1P5grWw0vIFO7fn3iIs',
    appId: '1:221648431679:ios:0b4093e0ece15595ca668a',
    messagingSenderId: '221648431679',
    projectId: 'increasecodes',
    storageBucket: 'increasecodes.appspot.com',
    iosBundleId: 'com.increasedw.increase',
  );
}
